# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rsocola
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: rest
# "service" is the name of this project. This will also be added to your AWS resource names.
service: CoffeApi

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  
  CreateCoffee:
    handler: services/createCoffe.handler
    events:
      - httpApi:
          path: /createCoffe
          method: post

  ListCoffees:
    handler: services/getCoffees.handler
    events:
      - httpApi:
          path: /ListCoffees
          method: get

  GetCoffeesById:
    handler: services/getCoffees.handler
    events:
      - httpApi:
          path: /GetCoffee/{id}
          method: get

  EditCoffees:
    handler: services/.handler
    events:
      - httpApi:
          path: /PutCoffee/{id}
          method: put

  DeleteCoffees:
    handler: service/delete.handler
    events:
      - httpApi:
          path: /DeleteCoffee/{id}
          method: delete